services:
  deep-learning:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /hdt
    volumes:
      - ./src:/hdt
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
